### ISSUE TITLE
Would be great to see you back on discord

### ISSUE THREAD

**Issue by batedk** [JMSDOnline/vstacklet#97]
API is down

**Comment by JMSDOnline** [comment]
Heya @batedk! It has been a while hasn't it! Thank you for the heads up on the API. I haven't had much time to get on the QB ball due to the house fire I had at the beginning of February. Nobody hurt, but lost pretty much everything. So progress in getting back to QB has been a very slow go... with that though, I am getting back to it by the end of this month as my living situation has finally sorted itself out and everything is slowly getting back in order (development-wise). I had to focus on other things in the meantime, obviously. 🤗 

As per the API, I logged into the site and was able to narrow down the issue, so things should be good on that front and everyone an reactivate their APIs without issue. Apologies for not notifying you guys, but there's just been so much going on and vStacklet got the update as this is my real job (design & development)

Again, thank you for the heads up and let everyone know I am ok and plan on getting back into Discord, hopefully by the end of this month.

**Comment by batedk** [comment]
<3 You've been missed. You do what to have to do. You know I will always support you. 
Please elevate my access to site and lab accessibility. Would be nice if we had other ways of communicating.

**Comment by JMSDOnline** [comment]
> <3 You've been missed. You do what to have to do. You know I will always support you. Please elevate my access to site and lab accessibility. Would be nice if we had other ways of communicating.

Definitely feel free to shoot me an email whenever at the addy set below. I will remove this comment chain once you confirm you've gotten it. I had to setup a new email account after the fire as I lost ***everything*** and lost access to all my login stuffs. I have all that back now, but currently it would be easiest for me to see anything if sent here until I am back and 100% setup for all the Q's I know I'll have! 🤣 

`persona.klutz(at)gmail(dot)com`
